name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Daimka
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Ulaanbaatar
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_url: https://www.16personalities.com/profiles/2ef57d1d6e9bb
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_gists: yes
